CREATE TABLE [dbo].[ShortenedUrls]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY,
	[OriginalUrl] VARCHAR(2048) NOT NULL,
	[GeneratedPath] VARCHAR(64) NOT NULL UNIQUE,
	[CreatedAt] DATETIME2 NOT NULL DEFAULT CURRENT_TIMESTAMP
)
